[GEAR-943] ENH - Readers group and readers progress report
flywheel-apps/nyu_rotator_cuff_gear_suite pull request #2
Opened 2021-05-11 15:39 UTC by dpark6060

Readers group is now the same group as the main project
Readers progress report is now generated with every gather cases run, indicating progress of current assigned cases and max cases
Fixed issues with list comprehension and flywheel permissions
In Readers projects, there can only be ONE user with "read-write" or "read-only" permissions, and that user MUST be the reader.  All other users can be admins or other roles.  Keep this in mind when using group-level permission templates.  

In my mind this is a problem that will hurt us later.  But hey, I just do what I'm told.

2021-05-14 14:53 UTC, AndysWorth commented
Assuming this is being used by customers and they are not complaining, LGTM.

2021-05-14 16:16 UTC, neurosutton commented on gears/assign_batch_cases/utils/manage_cases.py
> +    # valid_reader_ids = [
Do you want to clean up definitions that are not used anymore?

2021-05-14 16:30 UTC, neurosutton commented on gears/assign_batch_cases/utils/manage_cases.py
> +        if reader_email in dest_projects_df.reader_id.values:
Regarding your "more graceful way" in line 516, would it help to try:
``` python
project_id = dest_projects_df.loc[dest_projects_df['reader.id'] == reader_email, 'project_id']
```
and ditch line 511?

2021-05-14 16:37 UTC, neurosutton commented on gears/assign_cases/run.py
> +        # TODO: Verify that this isn't fucking something up.
Probably need to remove language for open resource.

2021-05-14 16:53 UTC, neurosutton requested changes
Please review commented line 33 in gears/assign_cases/run.py and see conversation comments for a couple of minor suggestions. Otherwise, LGTM.

2021-05-14 16:53 UTC, dpark6060 commented on gears/assign_batch_cases/utils/manage_cases.py
> +    # valid_reader_ids = [
commented definitions are the "original".  I had to expand the list comprehension to address an issue, and I want to leave them in until it's been vetted with a bunch of users, so I can always reference the original function incase there's something weird that gets messed up.

2021-05-19 13:42 UTC, dpark6060 commented on gears/assign_cases/run.py
> +        # TODO: Verify that this isn't fucking something up.
FINE

2021-05-19 14:11 UTC, AndysWorth commented on gears/assign_cases/run.py
> +        # TODO: Verify that this isn't fucking something up.
git blame knows all, tells all

2021-05-19 14:19 UTC, dpark6060 commented on gears/assign_cases/run.py
> +        # TODO: Verify that this isn't fucking something up.
# TODO: Verify that this isn't RUSTLING ANYONE'S JIMMIES

2021-05-19 14:31 UTC, dpark6060 commented on gears/assign_batch_cases/utils/manage_cases.py
> +        if reader_email in dest_projects_df.reader_id.values:
slight modifications, but done!  Thanks for the help.

2021-05-19 14:35 UTC, merged

2021-06-02 15:44 UTC, joshicola commented on gears/assign_cases/run.py
> +        # TODO: Verify that this isn't fucking something up.
hahahahahahahahahahahahahahahahahahahahahahaha!!!